"""Add table columns

Revision ID: 05f69c2ce116
Revises: fa1b18386c04
Create Date: 2024-10-15 19:11:14.251195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f69c2ce116'
down_revision = 'fa1b18386c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('items_available', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('offer_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('offer_price')
        batch_op.drop_column('items_available')
        batch_op.drop_column('category')
        batch_op.drop_column('price')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
