"""Add image_url and offer_price columns

Revision ID: 81e2915ed7fe
Revises: 9007d7cbbc63
Create Date: 2024-10-15 18:57:18.273512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e2915ed7fe'
down_revision = '9007d7cbbc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('offer_price')

    # ### end Alembic commands ###
