"""Remove image_url and offer_price columns

Revision ID: 9007d7cbbc63
Revises: 6ce74a0f75ba
Create Date: 2024-10-15 18:55:42.478796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9007d7cbbc63'
down_revision = '6ce74a0f75ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('offer_price')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('offer_price', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
