"""Add foreign key to CartItem

Revision ID: becd98f9cd35
Revises: 02ec5b05b374
Create Date: 2024-10-18 11:34:12.379348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becd98f9cd35'
down_revision = '02ec5b05b374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cart_items_order_id_orders'), 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cart_items_order_id_orders'), type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
