"""Rename columns

Revision ID: e0d15aab4b49
Revises: 81e2915ed7fe
Create Date: 2024-10-15 19:09:33.555164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d15aab4b49'
down_revision = '81e2915ed7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(), nullable=False))
        batch_op.drop_constraint('items_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['item_name'])
        batch_op.drop_column('name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.drop_constraint('users_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_name_key', ['name'])
        batch_op.drop_column('username')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('items_name_key', ['name'])
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
