"""Remove table columns

Revision ID: fa1b18386c04
Revises: e0d15aab4b49
Create Date: 2024-10-15 19:10:40.221282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1b18386c04'
down_revision = 'e0d15aab4b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('items_available')
        batch_op.drop_column('offer_price')
        batch_op.drop_column('description')
        batch_op.drop_column('category')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_email_key', ['email'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('offer_price', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('items_available', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
